plugins {
    id 'library.deps-conventions'
    id 'library.java-conventions'
    id 'library.publishing-conventions'
    id 'application'
}

dependencies {
    api(project(":telemetryvue-model"))
    runtimeOnly(project(":telemetryvue-h2"))
    implementation(project(":telemetryvue-receiver"))
    implementation(libs.grpc.netty.shadded)
    implementation(libs.grpc.protobuf)
    implementation(libs.grpc.stub)
    implementation(libs.opentelemetry.sdk)

    implementation("mil.army.usace.hec:lookup:2.0.1")
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}

run {
    mainClass = "mil.army.usace.hec.opentelemetry/telemetryvue/gui/TelemetryVue"
}