plugins {
    id 'library.deps-conventions'
    id 'library.java-conventions'
    id 'library.publishing-conventions'
}

dependencies {
    api(project(":local-telemetry-data-access"))

    implementation(libs.lookup)
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}

